---
name: "Run Tests"

on:
  - "push"
  - "pull_request"

jobs:
  run_tests:
    name: "Run Tests name"
    strategy:
      fail-fast: true
      matrix:
        os:
          - "ubuntu"
          - "macos"
        mpi-backend:
          - "mpich"
          - "openmpi"
        schism-version:
          - 5.8
        python-version:
          - "38"
          - "39"
    env:
      CONDA_LOCK_FILE: "conda-{{ matrix.os }}-64-p{{ matrix.python-version }}-s{{ matrix.schism-version }}-{{ matrix.mpi-backend }}.lock"

    runs-on: "${{ matrix.os }}-latest"
    defaults:
      run:
        shell: "bash -l {0}"
    steps:
      - name: "Checkout repo"
        uses: "actions/checkout@v2"

      - name: "Debug"
        uses: "hmarr/debug-action@v2"

      - name: "check matrix values"
        run: |
          echo {{ matrix.os }}
          echo {{ matrix.mpi-backend }}
          echo {{ matrix.schism-version }}
          echo {{ matrix.python-version }}

      - name: "check conda lock value"
        run: |
          echo {{ env.CONDA_LOCK_FILE }}
